/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique id assigned to the project.
 */
export type Id = string;
/**
 * The name of the project.
 */
export type Name = string;
/**
 * A description of the project.
 */
export type Description = string;
/**
 * The full name of the author.
 */
export type Name1 = string;
/**
 * The author's email address.
 */
export type Email = string;
/**
 * The author's host institute.
 */
export type Institute = string;
/**
 * The authors of the project.
 */
export type Authors = Author[];
/**
 * The unique id assigned to this study.
 */
export type Id1 = string;
/**
 * The id of the parent project.
 */
export type ProjectId = string;
/**
 * The name of the study.
 */
export type Name2 = string;
/**
 * A description of this study.
 */
export type Description1 = string;
/**
 * The unique id assigned to this optimization.
 */
export type Id2 = string;
/**
 * The id of the parent study.
 */
export type StudyId = string;
/**
 * The id of the parent project.
 */
export type ProjectId1 = string;
/**
 * The name of the optimization.
 */
export type Name3 = string;
/**
 * A description of this optimization.
 */
export type Description2 = string;
/**
 * The unique identifiers of the data sets to use as part of the optimization.
 */
export type TrainingSetIds = string[];
/**
 * The file name of the force field which will be used as the starting point for all optimizations.
 */
export type InitialForceField = ForceField;
/**
 * The xml representation of a force field in the SMIRNOFF force field format
 */
export type InnerXml = string;
/**
 * The type of the parameter handler associated with this parameter.
 */
export type HandlerType = string;
/**
 * The smirks identifier of the parameter.
 */
export type Smirks = string;
/**
 * The attribute name associated with the parameter.
 */
export type AttributeName = string;
/**
 * The force field parameters to be optimized.
 */
export type ParametersToTrain = Parameter[];
/**
 * The inputs to use for the optimization.
 */
export type ForceBalanceInput = ForceBalanceOptions;
/**
 * The maximum number of optimization iterations to perform.
 */
export type MaxIterations = number;
/**
 * The convergence criterion of the step size.
 */
export type ConvergenceStepCriteria = number;
/**
 * The convergence criterion of the objective function.
 */
export type ConvergenceObjectiveCriteria = number;
/**
 * The convergence criterion of the gradient norm.
 */
export type ConvergenceGradientCriteria = number;
/**
 * The number of convergence criteria that must be met for the optimizer to be declared converged.
 */
export type NCriteria = number;
/**
 * The name of the fitting target.
 */
export type TargetName = string;
/**
 * The chemical environments to consider when analysing the results of the optimization.
 */
export type AnalysisEnvironments = (
  | "Alkane"
  | "Cation"
  | "Anion"
  | "Carbonyl"
  | "Aldehyde"
  | "Ketone"
  | "Thiocarbonyl"
  | "Thioaldehyde"
  | "Thioketone"
  | "Imine"
  | "Hydrazone"
  | "Semicarbazone"
  | "Thiosemicarbazone"
  | "Oxime"
  | "Oxime Ether"
  | "Ketene"
  | "Ketene Acetal Derivative"
  | "Carbonyl Hydrate"
  | "Hemiacetal"
  | "Acetal"
  | "Hemiaminal"
  | "Aminal"
  | "Thiohemiaminal"
  | "Thioacetal"
  | "Enamine"
  | "Enol"
  | "Enolether"
  | "Hydroxy"
  | "Alcohol"
  | "Primary Alcohol"
  | "Secondary Alcohol"
  | "Tertiary Alcohol"
  | "1,2 Diol"
  | "1,2 Aminoalcohol"
  | "Phenol"
  | "1,2 Diphenol"
  | "Enediol"
  | "Ether"
  | "Dialkylether"
  | "Alkylarylether"
  | "Diarylether"
  | "Thioether"
  | "Disulfide"
  | "Peroxide"
  | "Hydroperoxide"
  | "Hydrazine"
  | "Hydroxylamine"
  | "Amine"
  | "Primary Amine"
  | "Primary Aliphatic Amine"
  | "Primary Aromatic Amine"
  | "Secondary Amine"
  | "Secondary Aliphatic Amine"
  | "Secondary Mixed Amine"
  | "Secondary Aromatic Amine"
  | "Tertiary Amine"
  | "Tertiary Aliphatic Amine"
  | "Tertiary Mixed Amine"
  | "Tertiary Aromatic Amine"
  | "Quart Ammonium"
  | "NOxide"
  | "Halogen Derivative"
  | "Alkyl Halide"
  | "Alkyl Fluoride"
  | "Alkyl Chloride"
  | "Alkyl Bromide"
  | "Alkyl Iodide"
  | "Aryl Halide"
  | "Aryl Fluoride"
  | "Aryl Chloride"
  | "Aryl Bromide"
  | "Aryl Iodide"
  | "Organometallic"
  | "Organolithium"
  | "Organomagnesium"
  | "Carboxylic Acid Derivative"
  | "Carboxylic Acid"
  | "Carboxylic Acid Salt"
  | "Carboxylic Acid Ester"
  | "Lactone"
  | "Carboxylic Acid Amide"
  | "Carboxylic Acid Primary Amide"
  | "Carboxylic Acid Secondary Amide"
  | "Carboxylic Acid Tertiary Amide"
  | "Lactam"
  | "Carboxylic Acid Hydrazide"
  | "Carboxylic Acid Azide"
  | "Hydroxamic Acid"
  | "Carboxylic Acid Amidine"
  | "Carboxylic Acid Amidrazone"
  | "Nitrile"
  | "Acyl Halide"
  | "Acyl Fluoride"
  | "Acyl Chloride"
  | "Acyl Bromide"
  | "Acyl Iodide"
  | "Acyl Cyanide"
  | "Imido Ester"
  | "Imidoyl Halide"
  | "Thiocarboxylic Acid Derivative"
  | "Thiocarboxylic Acid"
  | "Thiocarboxylic Acid Ester"
  | "Thiolactone"
  | "Thiocarboxylic Acid Amide"
  | "Thiolactam"
  | "Imido Thioester"
  | "Oxohetarene"
  | "Thioxohetarene"
  | "Iminohetarene"
  | "Orthocarboxylic Acid Derivative"
  | "Carboxylic Acid Orthoester"
  | "Carboxylic Acid Amide Acetal"
  | "Carboxylic Acid Anhydride"
  | "Carboxylic Acid Imide"
  | "Carboxylic Acid Unsubst Imide"
  | "Carboxylic Acid Subst Imide"
  | "CO2 Derivative"
  | "Carbonic Acid Derivative"
  | "Carbonic Acid Monoester"
  | "Carbonic Acid Diester"
  | "Carbonic Acid Ester Halide"
  | "Thiocarbonic Acid Derivative"
  | "Thiocarbonic Acid Monoester"
  | "Thiocarbonic Acid Diester"
  | "Thiocarbonic Acid Ester Halide"
  | "Carbamic Acid Derivative"
  | "Carbamic Acid"
  | "Carbamic Acid Ester"
  | "Carbamic Acid Halide"
  | "Thiocarbamic Acid Derivative"
  | "Thiocarbamic Acid"
  | "Thiocarbamic Acid Ester"
  | "Thiocarbamic Acid Halide"
  | "Urea"
  | "Isourea"
  | "Thiourea"
  | "Isothiourea"
  | "Guanidine"
  | "Semicarbazide"
  | "Thiosemicarbazide"
  | "Azide"
  | "Azo Compound"
  | "Diazonium Salt"
  | "Isonitrile"
  | "Cyanate"
  | "Isocyanate"
  | "Thiocyanate"
  | "Isothiocyanate"
  | "Carbodiimide"
  | "Nitroso Compound"
  | "Nitro Compound"
  | "Nitrite"
  | "Nitrate"
  | "Sulfuric Acid Derivative"
  | "Sulfuric Acid"
  | "Sulfuric Acid Monoester"
  | "Sulfuric Acid Diester"
  | "Sulfuric Acid Amide Ester"
  | "Sulfuric Acid Amide"
  | "Sulfuric Acid Diamide"
  | "Sulfuryl Halide"
  | "Sulfonic Acid Derivative"
  | "Sulfonic Acid"
  | "Sulfonic Acid Ester"
  | "Sulfonamide"
  | "Sulfonyl Halide"
  | "Sulfone"
  | "Sulfoxide"
  | "Sulfinic Acid Derivative"
  | "Sulfinic Acid"
  | "Sulfinic Acid Ester"
  | "Sulfinic Acid Halide"
  | "Sulfinic Acid Amide"
  | "Sulfenic Acid Derivative"
  | "Sulfenic Acid"
  | "Sulfenic Acid Ester"
  | "Sulfenic Acid Halide"
  | "Sulfenic Acid Amide"
  | "Thiol"
  | "Alkylthiol"
  | "Arylthiol"
  | "Phosphoric Acid Derivative"
  | "Phosphoric Acid"
  | "Phosphoric Acid Ester"
  | "Phosphoric Acid Halide"
  | "Phosphoric Acid Amide"
  | "Thiophosphoric Acid Derivative"
  | "Thiophosphoric Acid"
  | "Thiophosphoric Acid Ester"
  | "Thiophosphoric Acid Halide"
  | "Thiophosphoric Acid Amide"
  | "Phosphonic Acid Derivative"
  | "Phosphonic Acid"
  | "Phosphonic Acid Ester"
  | "Phosphine"
  | "Phosphinoxide"
  | "Boronic Acid Derivative"
  | "Boronic Acid"
  | "Boronic Acid Ester"
  | "Alkene"
  | "Alkyne"
  | "Aromaticatic"
  | "Heterocycle"
  | "Alpha Aminoacid"
  | "Alpha Hydroxyacid"
)[];
/**
 * The optimizations to perform as part of this study.
 */
export type Optimizations = Optimization[];
/**
 * The unique id assigned to this benchmark.
 */
export type Id3 = string;
/**
 * The id of the parent study.
 */
export type StudyId1 = string;
/**
 * The id of the parent project.
 */
export type ProjectId2 = string;
/**
 * The name of the benchmark.
 */
export type Name4 = string;
/**
 * A description of this benchmark.
 */
export type Description3 = string;
/**
 * The unique identifiers of the data sets to use as part of the benchmarking.
 */
export type TestSetIds = string[];
/**
 * The id of the optimization that should be benchmarked. This must be the id of an optimization which is part of the same study and project. This option is mutually exclusive with `force_field_name`.
 */
export type OptimizationId = string;
/**
 * The file name of the force field to use in the benchmark. This must be the name of a force field in the `openforcefields` GitHub repository. This option is mutually exclusive with `optimized_id`.
 */
export type ForceFieldName = string;
/**
 * The chemical environments to consider when analysing the results of the benchmark.
 */
export type AnalysisEnvironments1 = (
  | "Alkane"
  | "Cation"
  | "Anion"
  | "Carbonyl"
  | "Aldehyde"
  | "Ketone"
  | "Thiocarbonyl"
  | "Thioaldehyde"
  | "Thioketone"
  | "Imine"
  | "Hydrazone"
  | "Semicarbazone"
  | "Thiosemicarbazone"
  | "Oxime"
  | "Oxime Ether"
  | "Ketene"
  | "Ketene Acetal Derivative"
  | "Carbonyl Hydrate"
  | "Hemiacetal"
  | "Acetal"
  | "Hemiaminal"
  | "Aminal"
  | "Thiohemiaminal"
  | "Thioacetal"
  | "Enamine"
  | "Enol"
  | "Enolether"
  | "Hydroxy"
  | "Alcohol"
  | "Primary Alcohol"
  | "Secondary Alcohol"
  | "Tertiary Alcohol"
  | "1,2 Diol"
  | "1,2 Aminoalcohol"
  | "Phenol"
  | "1,2 Diphenol"
  | "Enediol"
  | "Ether"
  | "Dialkylether"
  | "Alkylarylether"
  | "Diarylether"
  | "Thioether"
  | "Disulfide"
  | "Peroxide"
  | "Hydroperoxide"
  | "Hydrazine"
  | "Hydroxylamine"
  | "Amine"
  | "Primary Amine"
  | "Primary Aliphatic Amine"
  | "Primary Aromatic Amine"
  | "Secondary Amine"
  | "Secondary Aliphatic Amine"
  | "Secondary Mixed Amine"
  | "Secondary Aromatic Amine"
  | "Tertiary Amine"
  | "Tertiary Aliphatic Amine"
  | "Tertiary Mixed Amine"
  | "Tertiary Aromatic Amine"
  | "Quart Ammonium"
  | "NOxide"
  | "Halogen Derivative"
  | "Alkyl Halide"
  | "Alkyl Fluoride"
  | "Alkyl Chloride"
  | "Alkyl Bromide"
  | "Alkyl Iodide"
  | "Aryl Halide"
  | "Aryl Fluoride"
  | "Aryl Chloride"
  | "Aryl Bromide"
  | "Aryl Iodide"
  | "Organometallic"
  | "Organolithium"
  | "Organomagnesium"
  | "Carboxylic Acid Derivative"
  | "Carboxylic Acid"
  | "Carboxylic Acid Salt"
  | "Carboxylic Acid Ester"
  | "Lactone"
  | "Carboxylic Acid Amide"
  | "Carboxylic Acid Primary Amide"
  | "Carboxylic Acid Secondary Amide"
  | "Carboxylic Acid Tertiary Amide"
  | "Lactam"
  | "Carboxylic Acid Hydrazide"
  | "Carboxylic Acid Azide"
  | "Hydroxamic Acid"
  | "Carboxylic Acid Amidine"
  | "Carboxylic Acid Amidrazone"
  | "Nitrile"
  | "Acyl Halide"
  | "Acyl Fluoride"
  | "Acyl Chloride"
  | "Acyl Bromide"
  | "Acyl Iodide"
  | "Acyl Cyanide"
  | "Imido Ester"
  | "Imidoyl Halide"
  | "Thiocarboxylic Acid Derivative"
  | "Thiocarboxylic Acid"
  | "Thiocarboxylic Acid Ester"
  | "Thiolactone"
  | "Thiocarboxylic Acid Amide"
  | "Thiolactam"
  | "Imido Thioester"
  | "Oxohetarene"
  | "Thioxohetarene"
  | "Iminohetarene"
  | "Orthocarboxylic Acid Derivative"
  | "Carboxylic Acid Orthoester"
  | "Carboxylic Acid Amide Acetal"
  | "Carboxylic Acid Anhydride"
  | "Carboxylic Acid Imide"
  | "Carboxylic Acid Unsubst Imide"
  | "Carboxylic Acid Subst Imide"
  | "CO2 Derivative"
  | "Carbonic Acid Derivative"
  | "Carbonic Acid Monoester"
  | "Carbonic Acid Diester"
  | "Carbonic Acid Ester Halide"
  | "Thiocarbonic Acid Derivative"
  | "Thiocarbonic Acid Monoester"
  | "Thiocarbonic Acid Diester"
  | "Thiocarbonic Acid Ester Halide"
  | "Carbamic Acid Derivative"
  | "Carbamic Acid"
  | "Carbamic Acid Ester"
  | "Carbamic Acid Halide"
  | "Thiocarbamic Acid Derivative"
  | "Thiocarbamic Acid"
  | "Thiocarbamic Acid Ester"
  | "Thiocarbamic Acid Halide"
  | "Urea"
  | "Isourea"
  | "Thiourea"
  | "Isothiourea"
  | "Guanidine"
  | "Semicarbazide"
  | "Thiosemicarbazide"
  | "Azide"
  | "Azo Compound"
  | "Diazonium Salt"
  | "Isonitrile"
  | "Cyanate"
  | "Isocyanate"
  | "Thiocyanate"
  | "Isothiocyanate"
  | "Carbodiimide"
  | "Nitroso Compound"
  | "Nitro Compound"
  | "Nitrite"
  | "Nitrate"
  | "Sulfuric Acid Derivative"
  | "Sulfuric Acid"
  | "Sulfuric Acid Monoester"
  | "Sulfuric Acid Diester"
  | "Sulfuric Acid Amide Ester"
  | "Sulfuric Acid Amide"
  | "Sulfuric Acid Diamide"
  | "Sulfuryl Halide"
  | "Sulfonic Acid Derivative"
  | "Sulfonic Acid"
  | "Sulfonic Acid Ester"
  | "Sulfonamide"
  | "Sulfonyl Halide"
  | "Sulfone"
  | "Sulfoxide"
  | "Sulfinic Acid Derivative"
  | "Sulfinic Acid"
  | "Sulfinic Acid Ester"
  | "Sulfinic Acid Halide"
  | "Sulfinic Acid Amide"
  | "Sulfenic Acid Derivative"
  | "Sulfenic Acid"
  | "Sulfenic Acid Ester"
  | "Sulfenic Acid Halide"
  | "Sulfenic Acid Amide"
  | "Thiol"
  | "Alkylthiol"
  | "Arylthiol"
  | "Phosphoric Acid Derivative"
  | "Phosphoric Acid"
  | "Phosphoric Acid Ester"
  | "Phosphoric Acid Halide"
  | "Phosphoric Acid Amide"
  | "Thiophosphoric Acid Derivative"
  | "Thiophosphoric Acid"
  | "Thiophosphoric Acid Ester"
  | "Thiophosphoric Acid Halide"
  | "Thiophosphoric Acid Amide"
  | "Phosphonic Acid Derivative"
  | "Phosphonic Acid"
  | "Phosphonic Acid Ester"
  | "Phosphine"
  | "Phosphinoxide"
  | "Boronic Acid Derivative"
  | "Boronic Acid"
  | "Boronic Acid Ester"
  | "Alkene"
  | "Alkyne"
  | "Aromaticatic"
  | "Heterocycle"
  | "Alpha Aminoacid"
  | "Alpha Hydroxyacid"
)[];
/**
 * The benchmarks to perform as part of this study.
 */
export type Benchmarks = Benchmark[];
/**
 * The studies conducted as part of the project.
 */
export type Studies = Study[];
/**
 * A collection of projects.
 */
export type Projects = Project[];

export interface ProjectCollection {
  projects?: Projects;
  [k: string]: unknown;
}
export interface Project {
  id: Id;
  name: Name;
  description: Description;
  authors: Authors;
  studies?: Studies;
  [k: string]: unknown;
}
export interface Author {
  name: Name1;
  email: Email;
  institute: Institute;
  [k: string]: unknown;
}
export interface Study {
  id: Id1;
  project_id: ProjectId;
  name: Name2;
  description: Description1;
  optimizations?: Optimizations;
  benchmarks?: Benchmarks;
  [k: string]: unknown;
}
export interface Optimization {
  id: Id2;
  study_id: StudyId;
  project_id: ProjectId1;
  name: Name3;
  description: Description2;
  training_set_ids: TrainingSetIds;
  initial_force_field: InitialForceField;
  parameters_to_train: ParametersToTrain;
  force_balance_input?: ForceBalanceInput;
  denominators: Denominators;
  priors: Priors;
  analysis_environments: AnalysisEnvironments;
  [k: string]: unknown;
}
export interface ForceField {
  inner_xml: InnerXml;
  [k: string]: unknown;
}
export interface Parameter {
  handler_type: HandlerType;
  smirks: Smirks;
  attribute_name: AttributeName;
  [k: string]: unknown;
}
export interface ForceBalanceOptions {
  max_iterations?: MaxIterations;
  convergence_step_criteria?: ConvergenceStepCriteria;
  convergence_objective_criteria?: ConvergenceObjectiveCriteria;
  convergence_gradient_criteria?: ConvergenceGradientCriteria;
  n_criteria?: NCriteria;
  target_name?: TargetName;
  [k: string]: unknown;
}
/**
 * The denominators to scale each class of properties contribution to the objective function by.
 */
export interface Denominators {
  [k: string]: string;
}
/**
 * The priors to place on each class of parameter.
 */
export interface Priors {
  [k: string]: number;
}
export interface Benchmark {
  id: Id3;
  study_id: StudyId1;
  project_id: ProjectId2;
  name: Name4;
  description: Description3;
  test_set_ids: TestSetIds;
  optimization_id: OptimizationId;
  force_field_name: ForceFieldName;
  analysis_environments: AnalysisEnvironments1;
  [k: string]: unknown;
}
